test:
  image: golang:1.17
  script:
    - go build -v ./...
    - go test -v ./...

scan:
  image: golang:1.17
  script:
    - go install github.com/praetorian-inc/gokart@latest
    - gokart scan

lint:
  image:
    name: github/super-linter
    entrypoint: [""]
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR 
  script:
    - /action/lib/linter.sh
