version: "2"

run:
  concurrency: 4
  tests: true
  allow-parallel-runners: true
  go: '1.24'

linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:

      - linters:
          - errcheck
          - gosec
          - staticcheck
        path: test.go

    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$