name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
      - run: go build -v ./...
      - run: go test -v -race ./...
      - uses: golangci/golangci-lint-action@v8

  docker:
    needs: test
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_SRE_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          provenance: mode=max
          sbom: true
          tags: ghcr.io/immobiliare/peephole:next
          push: true
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GH_SRE_TOKEN }}
