name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build -v ./...
      - run: go test -v ./...
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: |
          go install github.com/praetorian-inc/gokart@latest
          gokart scan
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://github/super-linter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PEEPHOLE }}
          VALIDATE_ALL_CODEBASE: true
