name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go build -v ./...
      - run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker://github/super-linter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PEEPHOLE }}
          VALIDATE_ALL_CODEBASE: false
  docker: 
    needs: [test, lint]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_SRE_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/immobiliare/peephole:next
          push: true
